import PySimpleGUI as sg
def page_conversor():
    sg.theme_background_color("white")
    cabecalho = [sg.Image(filename="img\cabecalho.png", background_color="white", pad=(0,(0,20)),)]
    valor_equivalente = [
        [sg.Image(filename="img//Valor Moeda.png", background_color="white",pad=(0,(0,5)), k="valor_moeda")],
        [sg.Input("", background_color="white", border_width=0, font="Inter 12 bold", justification="c", focus=True, k="valor")],
        [sg.Image(filename="img\Line 1.png", background_color="white", pad=(0,(0,0)))],
    ]
    
    pais_equivalente = [sg.OptionMenu([
        "AED - Dirham dos Emirados",
"AFN - Afghani do Afeganistão",
"ALL - Lek Albanês",
"AMD - Dram Armênio",
"ANG - Guilder das Antilhas",
"AOA - Kwanza Angolano",
"ARS - Peso Argentino",
"AUD - Dólar Australiano",
"AZN - Manat Azeri",
"BAM - Marco Conversível",
"BBD - Dólar de Barbados",
"BDT - Taka de Bangladesh",
"BGN - Lev Búlgaro",
"BHD - Dinar do Bahrein",
"BIF - Franco Burundinense",
"BND - Dólar de Brunei",
"BOB - Boliviano",
"BRL - Real Brasileiro",
"BSD - Dólar das Bahamas",
"BTC - Bitcoin",
"BWP - Pula de Botswana",
"BYN - Rublo Bielorrusso",
"BZD - Dólar de Belize",
"CAD - Dólar Canadense",
"CHF - Franco Suíço",
"CLP - Peso Chileno",
"CNH - Yuan chinês offshore",
"CNY - Yuan Chinês",
"COP - Peso Colombiano",
"CRC - Colón Costarriquenho",
"CUP - Peso Cubano",
"CVE - Escudo cabo-verdiano",
"CZK - Coroa Checa",
"DJF - Franco do Djubouti",
"DKK - Coroa Dinamarquesa",
"DOP - Peso Dominicano",
"DZD - Dinar Argelino",
"EGP - Libra Egípcia",
"ETB - Birr Etíope",
"ETH - Ethereum",
"EUR - Euro",
"FJD - Dólar de Fiji",
"GBP - Libra Esterlina",
"GEL - Lari Georgiano",
"GHS - Cedi Ganês",
"GMD - Dalasi da Gâmbia",
"GNF - Franco de Guiné",
"GTQ - Quetzal Guatemalteco",
"HKD - Dólar de Hong Kong",
"HNL - Lempira Hondurenha",
"HRK - Kuna Croata",
"HTG - Gourde Haitiano",
"HUF - Florim Húngaro",
"IDR - Rupia Indonésia",
"ILS - Novo Shekel Israelense",
"INR - Rúpia Indiana",
"IQD - Dinar Iraquiano",
"IRR - Rial Iraniano",
"ISK - Coroa Islandesa",
"JMD - Dólar Jamaicano",
"JOD - Dinar Jordaniano",
"JPY - Iene Japonês",
"KES - Shilling Queniano",
"KGS - Som Quirguistanês",
"KHR - Riel Cambojano",
"KMF - Franco Comorense",
"KRW - Won Sul-Coreano",
"KWD - Dinar Kuwaitiano",
"KYD - Dólar das Ilhas Cayman",
"KZT - Tengue Cazaquistanês",
"LAK - Kip Laosiano",
"LBP - Libra Libanesa",
"LKR - Rúpia de Sri Lanka",
"LSL - Loti do Lesoto",
"LTC - Litecoin",
"LYD - Dinar Líbio",
"MAD - Dirham Marroquino",
"MDL - Leu Moldavo",
"MGA - Ariary Madagascarense",
"MKD - Denar Macedônio",
"MMK - Kyat de Mianmar",
"MNT - Mongolian Tugrik",
"MOP - Pataca de Macau",
"MRO - Ouguiya Mauritana",
"MUR - Rúpia Mauriciana",
"MVR - Rufiyaa Maldiva",
"MWK - Kwacha Malauiana",
"MXN - Peso Mexicano",
"MYR - Ringgit Malaio",
"MZN - Metical de Moçambique",
"NAD - Dólar Namíbio",
"NGN - Naira Nigeriana",
"NIO - Córdoba Nicaraguense",
"NOK - Coroa Norueguesa",
"NPR - Rúpia Nepalesa",
"NZD - Dólar Neozelandês",
"OMR - Rial Omanense",
"PAB - Balboa Panamenho",
"PEN - Sol do Peru",
"PGK - Kina Papua-Nova Guiné",
"PHP - Peso Filipino",
"PKR - Rúpia Paquistanesa",
"PLN - Zlóti Polonês",
"PYG - Guarani Paraguaio",
"QAR - Rial Catarense",
"RON - Leu Romeno",
"RSD - Dinar Sérvio",
"RUB - Rublo Russo",
"RWF - Franco Ruandês",
"SAR - Riyal Saudita",
"SCR - Rúpias de Seicheles",
"SDG - Libra Sudanesa",
"SEK - Coroa Sueca",
"SGD - Dólar de Cingapura",
"SOS - Shilling Somaliano",
"STD - Dobra São Tomé/Príncipe",
"SVC - Colon de El Salvador",
"SYP - Libra Síria",
"SZL - Lilangeni Suazilandês",
"THB - Baht Tailandês",
"TJS - Somoni do Tajiquistão",
"TND - Dinar Tunisiano",
"TRY - Nova Lira Turca",
"TTD - Dólar de Trinidad",
"TWD - Dólar Taiuanês",
"TZS - Shilling Tanzaniano",
"UAH - Hryvinia Ucraniana",
"UGX - Shilling Ugandês",
"USD - Dólar Americano",
"UYU - Peso Uruguaio",
"UZS - Som Uzbequistanês",
"VEF - Bolívar Venezuelano",
"VND - Dong Vietnamita",
"VUV - Vatu de Vanuatu",
"XAF - Franco CFA Central",
"XBR - Brent Spot",
"XCD - Dólar do Caribe Oriental",
"XOF - Franco CFA Ocidental",
"XPF - Franco CFP",
"YER - Riyal Iemenita",
"ZAR - Rand Sul-Africano",
"ZMK - Kwacha Zambiana",
"ZWL - Dólar Zimbabuense",],auto_size_text=True, k="equivalente",background_color="white",text_color="green",pad=(0,(0,0)))]
    pais_equivalecia = [sg.OptionMenu([
        "AED - Dirham dos Emirados",
"AFN - Afghani do Afeganistão",
"ALL - Lek Albanês",
"AMD - Dram Armênio",
"ANG - Guilder das Antilhas",
"AOA - Kwanza Angolano",
"ARS - Peso Argentino",
"AUD - Dólar Australiano",
"AZN - Manat Azeri",
"BAM - Marco Conversível",
"BBD - Dólar de Barbados",
"BDT - Taka de Bangladesh",
"BGN - Lev Búlgaro",
"BHD - Dinar do Bahrein",
"BIF - Franco Burundinense",
"BND - Dólar de Brunei",
"BOB - Boliviano",
"BRL - Real Brasileiro",
"BSD - Dólar das Bahamas",
"BTC - Bitcoin",
"BWP - Pula de Botswana",
"BYN - Rublo Bielorrusso",
"BZD - Dólar de Belize",
"CAD - Dólar Canadense",
"CHF - Franco Suíço",
"CLP - Peso Chileno",
"CNH - Yuan chinês offshore",
"CNY - Yuan Chinês",
"COP - Peso Colombiano",
"CRC - Colón Costarriquenho",
"CUP - Peso Cubano",
"CVE - Escudo cabo-verdiano",
"CZK - Coroa Checa",
"DJF - Franco do Djubouti",
"DKK - Coroa Dinamarquesa",
"DOP - Peso Dominicano",
"DZD - Dinar Argelino",
"EGP - Libra Egípcia",
"ETB - Birr Etíope",
"ETH - Ethereum",
"EUR - Euro",
"FJD - Dólar de Fiji",
"GBP - Libra Esterlina",
"GEL - Lari Georgiano",
"GHS - Cedi Ganês",
"GMD - Dalasi da Gâmbia",
"GNF - Franco de Guiné",
"GTQ - Quetzal Guatemalteco",
"HKD - Dólar de Hong Kong",
"HNL - Lempira Hondurenha",
"HRK - Kuna Croata",
"HTG - Gourde Haitiano",
"HUF - Florim Húngaro",
"IDR - Rupia Indonésia",
"ILS - Novo Shekel Israelense",
"INR - Rúpia Indiana",
"IQD - Dinar Iraquiano",
"IRR - Rial Iraniano",
"ISK - Coroa Islandesa",
"JMD - Dólar Jamaicano",
"JOD - Dinar Jordaniano",
"JPY - Iene Japonês",
"KES - Shilling Queniano",
"KGS - Som Quirguistanês",
"KHR - Riel Cambojano",
"KMF - Franco Comorense",
"KRW - Won Sul-Coreano",
"KWD - Dinar Kuwaitiano",
"KYD - Dólar das Ilhas Cayman",
"KZT - Tengue Cazaquistanês",
"LAK - Kip Laosiano",
"LBP - Libra Libanesa",
"LKR - Rúpia de Sri Lanka",
"LSL - Loti do Lesoto",
"LTC - Litecoin",
"LYD - Dinar Líbio",
"MAD - Dirham Marroquino",
"MDL - Leu Moldavo",
"MGA - Ariary Madagascarense",
"MKD - Denar Macedônio",
"MMK - Kyat de Mianmar",
"MNT - Mongolian Tugrik",
"MOP - Pataca de Macau",
"MRO - Ouguiya Mauritana",
"MUR - Rúpia Mauriciana",
"MVR - Rufiyaa Maldiva",
"MWK - Kwacha Malauiana",
"MXN - Peso Mexicano",
"MYR - Ringgit Malaio",
"MZN - Metical de Moçambique",
"NAD - Dólar Namíbio",
"NGN - Naira Nigeriana",
"NIO - Córdoba Nicaraguense",
"NOK - Coroa Norueguesa",
"NPR - Rúpia Nepalesa",
"NZD - Dólar Neozelandês",
"OMR - Rial Omanense",
"PAB - Balboa Panamenho",
"PEN - Sol do Peru",
"PGK - Kina Papua-Nova Guiné",
"PHP - Peso Filipino",
"PKR - Rúpia Paquistanesa",
"PLN - Zlóti Polonês",
"PYG - Guarani Paraguaio",
"QAR - Rial Catarense",
"RON - Leu Romeno",
"RSD - Dinar Sérvio",
"RUB - Rublo Russo",
"RWF - Franco Ruandês",
"SAR - Riyal Saudita",
"SCR - Rúpias de Seicheles",
"SDG - Libra Sudanesa",
"SEK - Coroa Sueca",
"SGD - Dólar de Cingapura",
"SOS - Shilling Somaliano",
"STD - Dobra São Tomé/Príncipe",
"SVC - Colon de El Salvador",
"SYP - Libra Síria",
"SZL - Lilangeni Suazilandês",
"THB - Baht Tailandês",
"TJS - Somoni do Tajiquistão",
"TND - Dinar Tunisiano",
"TRY - Nova Lira Turca",
"TTD - Dólar de Trinidad",
"TWD - Dólar Taiuanês",
"TZS - Shilling Tanzaniano",
"UAH - Hryvinia Ucraniana",
"UGX - Shilling Ugandês",
"USD - Dólar Americano",
"UYU - Peso Uruguaio",
"UZS - Som Uzbequistanês",
"VEF - Bolívar Venezuelano",
"VND - Dong Vietnamita",
"VUV - Vatu de Vanuatu",
"XAF - Franco CFA Central",
"XBR - Brent Spot",
"XCD - Dólar do Caribe Oriental",
"XOF - Franco CFA Ocidental",
"XPF - Franco CFP",
"YER - Riyal Iemenita",
"ZAR - Rand Sul-Africano",
"ZMK - Kwacha Zambiana",
"ZWL - Dólar Zimbabuense",],auto_size_text=True, k="equivalecia",background_color="white",text_color="red",pad=(0,(0,0)))],
                    
    
    layout = [cabecalho, valor_equivalente,pais_equivalente, pais_equivalecia]
    window = sg.Window("Conversor", layout=layout, margins=(0,0), element_justification='c', size=(310,556))
    
    while True:
        event, values = window.read(timeout=1)
        
        
        if event == sg.WIN_CLOSED:
            break
        
        print(values["equivalente"][:3])
page_conversor()